### PR TITLE
Set the canonical homepage to fix Java publishing

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Apparently, `pulumi` and `Pulumi` are meaningfully different values for the `publisher` property in the schema, and `https://www.pulumi.com` and `https://pulumi.com` are different home pages. If both are set incorrectly, Java POM information won't be filled: https://github.com/pulumi/pulumi-java/blob/0f614b60a861e9e2faa2f798036dda6fddb4dba4/pkg/codegen/java/templates_gradle.go#L126-L129

Right now, the Java publishing step fails because POM values aren't set correctly. This PR should fix that.

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
🥲

**Review by VenelinMartinov — COMMENTED** [review]
Did we copy this from somewhere? should we fix it there too?

**Comment by blampe** [comment]
Fun! Some more

* https://github.com/pulumi/pulumi-docker-build/blob/c305ea88c49b158644618639dfc510c98a340e88/provider/internal/provider.go#L76
* https://github.com/pulumi/pulumi-scm/blob/ce6b781e09f82422fdcb7446bb8fc3509cefb02d/provider/resources.go#L58
* https://github.com/pulumi/pulumi-ise/blob/3e53d2d92267f05c190ffd1960a130cd9a06ebc0/provider/resources.go#L150
* https://github.com/pulumi/pulumi-sdwan/blob/262543eac8fd9e7faf9fed9298f35a9c9b3399d7/provider/resources.go#L58
* https://github.com/pulumi/pulumi-meraki/blob/86be07c3f3a0b531b3e52d9214671b1226377270/provider/resources.go#L135

**Comment by mikhailshilkov** [comment]
> Some more

Yeah, I'm about to fix those after this one succeeds to publish

**Review by t0yv0 — APPROVED** [review]

**Comment by iwahbe** [comment]
@mikhailshilkov Thanks for taking this! I'm going to open an issue in pulumi/pulumi-java to track an upstream fix. Invalid display names should either fail to generate an SDK or generate a publishable SDK.

**Pull request merged**
